apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dxpgateway
spec:
  storageClassName: {{ .Values.dgw.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sdcard
spec:
  storageClassName: {{ .Values.dgw.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
